#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export INSECURE_ADDRESS=${INSECURE_ADDRESS:="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"}
export INSECURE_PRIVATE_KEY=${INSECURE_PRIVATE_KEY:="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"}

function compile() {
  mkdir -p go/contract
  docker run --rm \
    -v $DIR:/src \
    -w /src \
    --entrypoint solc \
    binocarlos/solc:v1 \
      --abi --bin SimpleEvent.sol -o artifacts
  docker run --rm \
    -v $DIR:/src \
    -w /src \
    --entrypoint abigen \
    binocarlos/solc:v1 \
      --bin=artifacts/SimpleEvent.bin --abi=artifacts/SimpleEvent.abi --pkg=contract --out=go/contract/contract.go
  sudo chown -R $USER:$USER go
  sudo chown -R $USER:$USER artifacts
  sudo chmod 0644 go/contract/contract.go
}

function clean() {
  rm -rf artifacts
}

function geth() {
  docker run -d --restart always \
    --name geth \
    -p 8545:8545 \
    -p 8546:8546 \
    ethereum/client-go \
      --datadir /data/geth \
      --dev \
      --ws \
      --ws.api web3,eth,net \
      --ws.addr 0.0.0.0 \
      --ws.port 8546 \
      --ws.origins '*' \
      --http \
      --http.api web3,eth,net \
      --http.addr 0.0.0.0 \
      --http.corsdomain '*' \
      --http.port 8545 \
      --http.vhosts '*'
}

function geth-command() {
  docker exec -i geth geth --exec "$@" attach /data/geth/geth.ipc
}

function geth-fund() {
  geth-command "eth.sendTransaction({from: eth.coinbase, to: \"${INSECURE_ADDRESS}\", value: new web3.BigNumber(eth.getBalance(eth.coinbase)).minus(web3.toWei(1, \"ether\"))  })"
  echo
  echo "export PRIVATE_KEY=$INSECURE_PRIVATE_KEY"
  echo "export RPC_URL=ws://127.0.0.1:8546"
  echo "export CHAIN_ID=1337"
}

eval "$@"
